# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shop-video"
client_id = "a63ea7bc012b4a51a9401bfd627a7667"
application_url = "https://jar-ticket-plug-gap.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://jar-ticket-plug-gap.trycloudflare.com/auth/callback",
  "https://jar-ticket-plug-gap.trycloudflare.com/auth/shopify/callback",
  "https://jar-ticket-plug-gap.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-a233b7ae.myshopify.com"
